options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "asia-northeast1"

steps:
  # 1) Build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA",
        "-f", "backend/Dockerfile",
        "backend"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "push", "gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA" ]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy cwdef \
          --image=gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA \
          --platform=managed \
          --region=$_REGION \
          --allow-unauthenticated 

images:
  - "gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA"
