options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "asia-northeast1"

steps:
  # 1) Build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA",
        "-f", "backend/Dockerfile",
        "backend"
      ]

  # 2) Push it
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "push", "gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA" ]

  # 3) Deploy to the single `cwdef` service
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy cwdef \
          --image=gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA \
          --platform=managed \
          --region=$_REGION \
          --allow-unauthenticated \
          --set-env-vars POSTGRES_HOST=$POSTGRES_HOST,POSTGRES_PORT=$POSTGRES_PORT,POSTGRES_DB=$POSTGRES_DB,POSTGRES_USER=$POSTGRES_USER,POSTGRES_PASSWORD=$POSTGRES_PASSWORD,SECRET_KEY=$SECRET_KEY,DEBUG=$DEBUG

images:
  - "gcr.io/$PROJECT_ID/cwdef-backend:$SHORT_SHA"
