# Generated by Django 5.2 on 2025-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.TextField(blank=True),
        ),
    ]
