# Generated by Django 5.2 on 2025-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_rename_date_event_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="club_rep",
            field=models.BooleanField(default=False),
        ),
    ]
