# Generated by Django 5.2 on 2025-05-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_club_rep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club_rep",
            field=models.BooleanField(default=True),
        ),
    ]
